name: "OrangeFox Build Action"
author: 'Ragebreaker'
description: "A GitHub action to build OrangeFox recovery for a specified device."

inputs:
  MANIFEST_BRANCH:
    description: 'OrangeFox Manifest Branch'
    default: '12.1'
    type: choice
    options:
    - 12.1
    - 11.0
  DEVICE_TREE:
    description: 'Custom Recovery Tree'
    default: ''
    type: string
  DEVICE_TREE_BRANCH:
    description: 'Custom Recovery Tree Branch (use default branch if not specified)'
    default: ''
    type: string
  DEVICE_NAME:
    description: 'Specify your Device Codename (leave blank to auto-detect)'
    default: ''
    type: string
  DEVICE_PATH:
    description: 'Specify your Device Path (leave blank to auto-detect from device tree)'
    default: ''
    type: string
  BUILD_TARGET:
    description: 'Specify your Build Target'
    default: 'recovery'
    type: choice
    options:
    - boot
    - recovery
    - vendorboot

runs:
  using: 'composite'
  steps:
    - name: Set up environment
      shell: bash
      run: |
        echo "MANIFEST_BRANCH=${{ inputs.MANIFEST_BRANCH }}" >> $GITHUB_ENV
        echo "DEVICE_TREE=${{ inputs.DEVICE_TREE }}" >> $GITHUB_ENV
        echo "DEVICE_TREE_BRANCH=${{ inputs.DEVICE_TREE_BRANCH }}" >> $GITHUB_ENV
        echo "DEVICE_NAME=${{ inputs.DEVICE_NAME }}" >> $GITHUB_ENV
        echo "DEVICE_PATH=${{ inputs.DEVICE_PATH }}" >> $GITHUB_ENV
        echo "BUILD_TARGET=${{ inputs.BUILD_TARGET }}" >> $GITHUB_ENV

    - name: 'Build ofox'
      shell: bash
      run: |
        bash $GITHUB_ACTION_PATH/entrypoint.sh

branding:
  icon: "terminal"
  color: "orange"
